### ISSUE TITLE
Support for multiple Kibana instances

### ISSUE THREAD

**Issue by hameno** [elastic/puppet-kibana#10]
### Feature Description
I think it would be useful to have the ability to manage multiple independent kibana instances, like the elasticsearch module does. We have different es clusters and we would like to have separate kibana instances which access these instances.

**Comment by tylerjl** [comment]
Thanks for the report @hameno. You're right that this is natively supported in the Elasticsearch module, but historically there have been problems with manually creating service files since they're defined separately from the upstream packages. I've opened up [an Elasticsearch issue](https://github.com/elastic/elasticsearch/issues/24867) to discuss the possibility of shipping templated systemd units with Elasticsearch and will open a similar discussion with Kibana if this sounds like a reasonable option for the projects, since instantiating services based on templated systemd service units would be the best way to do this going forward.

Just as a data point, what distro and version (both OS and kibana) would you be running multiple instances on?

**Comment by hameno** [comment]
We would be using Ubuntu (16.04 or whatever is current LTS)

**Comment by tylerjl** [comment]
See the comment [here](https://github.com/elastic/puppet-kibana/pull/25#issuecomment-480048401) and over in elastic/puppet-elasticsearch#1025 . If multiple instance support is a pretty crucial feature for some people, we can potentially add some helper documentation for the repo regarding how to achieve this with Docker - let me know if that's the case, and we can add to the README if so. :+1:
